#!/usr/bin/env python3
# fontconvert.py — faithful reimplementation of Adafruit_GFX fontconvert
# (TrueType -> Adafruit GFX .h). Uses freetype-py (same FreeType engine).
#
# Usage: python tools/font_convert.py <font.ttf> <size> <first> <last> <fontName> > out.h
#        e.g. python tools/font_convert.py Roboto-Regular.ttf 6 32 126 Roboto6 > firmware/src/fonts/Roboto6pt7b.h
#
# Matches Adafruit's fontconvert.c: DPI=141, FT_Set_Char_Size(size<<6), mono
# raster, advance = advance.x>>6, xOffset=bitmap_left, yOffset=1-bitmap_top,
# row-major MSB-first bit packing padded to a byte boundary per glyph.
#
# IMPORTANT: we load with FT_LOAD_TARGET_MONO | FT_LOAD_RENDER so FreeType uses
# its native mono hinting (pixel_mode==1) -- the same crisp, stem-snapping
# rasterization the library's shipped GFX Free Fonts were built with. Plain
# FT_LOAD_TARGET_MONO without FT_LOAD_RENDER falls back to gray (pixel_mode==2),
# and thresholding that produces the muddy stems seen in small TTF fonts.
import sys

import freetype

DPI = 141
LOAD_MONO = freetype.FT_LOAD_TARGET_MONO | freetype.FT_LOAD_RENDER


def mono_bytes(buf, pitch, rows, width):
    """Pack a mono-hinted bitmap (pixel_mode 1, one bit per pixel, MSB-first per
    byte) into the packed bytes fontconvert emits: row-major, glyph padded to a
    byte boundary. Only 'width' bits of each pitch-byte row are used."""
    out = bytearray()
    bit = 0x80
    cur = 0
    for y in range(rows):
        row_base = y * pitch
        for x in range(width):
            byte = buf[row_base + x // 8]
            if (byte >> (7 - (x & 7))) & 1:
                cur |= bit
            bit >>= 1
            if bit == 0:
                out.append(cur)
                cur = 0
                bit = 0x80
    if bit != 0x80:  # pad to byte boundary (fontconvert does this)
        out.append(cur)
    return out


def main():
    ttf, size, first, last, fontName = (
        sys.argv[1],
        float(sys.argv[2]),
        int(sys.argv[3]),
        int(sys.argv[4]),
        sys.argv[5],
    )
    fontName = "".join(
        "_" if (ch.isspace() or (not ch.isalnum() and ch != "_")) else ch for ch in fontName
    )
    fontName = fontName.replace("-", "_")

    face = freetype.Face(ttf)
    face.set_char_size(int(size * 64), 0, DPI, 0)
    yAdvance = face.size.height >> 6 if face.size else int(size)
    # Font name token: '5.5' -> '55', '5.0'/'5' -> '5' (drop the dot and any
    # trailing '.0' so integers get a clean token). Roboto 5pt -> Roboto5pt7b.
    sizeToken = ("%g" % size).replace(".", "")

    glyphs = []
    bitmapOffset = 0
    bitmap_bytes = bytearray()

    for code in range(first, last + 1):
        try:
            face.load_char(code, LOAD_MONO)
        except Exception:
            continue
        slot = face.glyph
        bmp = slot.bitmap
        w, rows, pitch = bmp.width, bmp.rows, bmp.pitch
        if w and rows:
            buf = bmp.buffer
            if not isinstance(buf, (bytes, bytearray)):
                buf = bytes(buf)
            b = mono_bytes(buf, pitch, rows, w)
        else:
            b = bytearray()
        xAdvance = slot.advance.x >> 6
        xo = slot.bitmap_left
        yo = 1 - slot.bitmap_top
        glyphs.append((bitmapOffset, w, rows, xAdvance, xo, yo, b))
        bitmap_bytes.extend(b)
        bitmapOffset += (w * rows + 7) // 8

    base = fontName + sizeToken + "pt7b"
    print("// Auto-generated by tools/font_convert.py (Adafruit_GFX fontconvert-compatible,")
    print("// FT_LOAD_TARGET_MONO|FT_LOAD_RENDER hinting).")
    print("// Include after gfxfont.h (GFXglyph/GFXfont) or define those types first.")
    print("#include <cstdint>")
    print(f"const uint8_t {base}Bitmaps[] PROGMEM = {{")
    line = "  "
    col = 0
    for i, byte in enumerate(bitmap_bytes):
        line += f"0x{byte:02X}, "
        col += 1
        if col >= 12:
            print(line.rstrip())
            line = "  "
            col = 0
    if line.strip():
        print(line.rstrip())
    print("};")
    print()
    print(f"const GFXglyph {base}Glyphs[] PROGMEM = {{")
    for bo, w, h, xa, xo, yo, b in glyphs:
        print(f"  {{ {bo:4d}, {w:3d}, {h:3d}, {xa:3d}, {xo:4d}, {yo:4d} }},")
    print("};")
    print()
    print(f"const GFXfont {base} PROGMEM = {{")
    print(f"  (uint8_t  *){base}Bitmaps,")
    print(f"  (GFXglyph *){base}Glyphs,")
    print(f"  0x{first:02X}, 0x{last:02X}, {yAdvance}}};")
    # A trailing newline, deliberately: these headers are committed, and the
    # end-of-file-fixer pre-commit hook rewrites (and thus aborts a commit over) any file
    # that lacks one — which repeatedly cost a re-stage here (LESSONS §57).
    print(f"// Approx. {bitmapOffset + (last - first + 1) * 7 + 7} bytes", end="\n")


if __name__ == "__main__":
    main()
